[project]
name = "ai-talent-hub-task-system-design"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiogram>=3.30.0",
    "faiss-cpu>=1.15.0",
    "fastapi>=0.141.1",
    "google-genai>=2.17.0",
    "langchain>=1.3.14",
    "langgraph>=1.2.10",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.15.0",
    "scikit-learn>=1.9.0",
    "torch>=2.13.0",
    "transformers>=5.14.1",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
